group: hervalicious
artifact: kb
version: 1.0.0-SNAPSHOT

repositories:
  - https://repo.maven.apache.org/maven2/

languages:
  - kotlin

dependencies:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.51
  - com.xenomachina:kotlin-argparser:2.0.7
  - com.fasterxml.jackson.core:jackson-databind:2.7.1-1
  - com.fasterxml.jackson.module:jackson-module-kotlin:2.7.1-2
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.7.1
  - org.freemarker:freemarker:2.3.20
  - org.python:jython:2.7.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version


test-dependencies:
  - junit:junit:4.12

main-class: kb.MainKt
