//
// WARNING: THIS FILE IS AUTOGENERATED BY kb. ANY MODIFICATIONS WILL BE IGNORED! 🤷‍♂️
//

<#list languages as language>
    <#if language == 'java'>
apply plugin: 'java'
    </#if>
    <#if language == 'kotlin'>
apply plugin: 'kotlin'
    </#if>
</#list>


<#if mainClass??>
apply plugin: 'application'
mainClassName = "${mainClass}"
</#if>

<#if jvmArgs??>
applicationDefaultJvmArgs = [${jvmArgs}]
</#if>

repositories {
    <#list repositories as repository>
        maven { url "${repository}" }
    </#list>
}

sourceSets {
    <#list sourcePaths as path>
        main.java.srcDirs += '${path}'
    </#list>
    <#list testPaths as path>
        test.java.srcDirs += '${path}'
    </#list>
}

dependencies {
    <#list dependencies as dependency>
        compile '${dependency}'
    </#list>

    <#list testDependencies as dependency>
        testCompile '${dependency}'
    </#list>
}


run {
    if (project.hasProperty('args')) {
        args project.args.split('\\s')
    }
}

//
// WARNING: THIS FILE IS AUTOGENERATED BY kb. ANY MODIFICATIONS WILL BE IGNORED! 🤷‍♂️
//
